### ISSUE TITLE
Include rustdoc in ABI schema

### ISSUE THREAD

**Issue by austinabell** [near/cargo-near#12]
As indicated by @zcstarr, it would be beneficial if the rustdocs from functions exposed by the contract and their types be included in the ABI.

This will come at the cost of increasing the size of the ABI, so we should consider making it an optional or opt-out flag if we introduce

**Comment by zcstarr** [comment]
One thing here is just relative cost, it might not be as expensive as you think. The other thing here would be the smaller the contract probably the less need for extensive docs so an opt out flag makes since.
