### ISSUE TITLE
Can not parse subcommand flatten

### ISSUE THREAD

**Issue by jong-un-crypto** [near/cargo-near#141]
interactive-clap = "0.2.8"
interactive-clap-derive = "0.2.8"

    #[interactive_clap(flatten)]
    /// Specify a build command args:
    build_command_args: build_command::BuildCommand,

error[E0609]: no field `build_command_args` on type `&commands::deploy::InteractiveClapContextScopeForContract`
  --> cargo-near/src/commands/deploy/mod.rs:29:57
   |
29 |         let file_path = build_command::build::run(scope.build_command_args.clone())?.path;
   |                                                         ^^^^^^^^^^^^^^^^^^ unknown field
   |
   = note: available field is: `contract_account_id`

error[E0560]: struct `commands::deploy::InteractiveClapContextScopeForContract` has no field named `build_command_args`
  --> cargo-near/src/commands/deploy/mod.rs:90:13
   |
90 |             build_command_args,
   |             ^^^^^^^^^^^^^^^^^^ `commands::deploy::InteractiveClapContextScopeForContract` does not have this field
   |
   = note: all struct fields are already assigned

**Comment by dj8yfo** [comment]
fixed by #154 and #155
