### ISSUE TITLE
Usage metrics

### ISSUE THREAD

**Issue by gagdiez** [near/cargo-near#185]
In `create-near-app` we have an incredibly simple, non-invasive, and anonymous way of gathering usage metrics though `mixpanel`.

Basically, each time `CNA` is used, a small payload is sent to `mixpanel` that includes which type of contract or frontend was created. Source code [here](https://github.com/near/create-near-app/blob/master/src/tracking.ts).

Would be nice to implement the same concept in `cargo near new`, so we can get back statistics from smart contracts created with rust.

**Comment by frol** [comment]
@gagdiez @garikbesson Have anyone flagged privacy concerns regarding the tracking in CLI?

https://github.com/near/near-cli-rs/issues/83 - I remember I started this issue, but then decided to close it as I was not completely comfortable pushing such code to the users. Even an empty HTTP call to mixpanel is already a traceable event which reveals IP, time, and potentially OS.

**Comment by gagdiez** [comment]
@frol never had any privacy concerns
