### ISSUE TITLE
Implement build command to build contract and ABI together

### ISSUE THREAD

**Issue by austinabell** [near/cargo-near#21]
Motivation is that it would be preferred if these are built together to ensure there is no mismatch of versions when using.

```
cargo near build
```

should build similar to `cargo build` except that it includes `"-C", "link-arg=-s"` rustflags to ensure those aren't left out and includes `--target wasm32-unknown-unknown`. Unsure if all cargo options should/can be forwarded easily, but at least `--release` needs to be included as configuration.

This command should output the following files in `$CARGO_TARGET_DIR/near/`:

- `<crate name>.json`: ABI of contract (logic exists already with `cargo near abi`)
- `<crate name>.wasm`: Built wasm file
- `<crate name>.<extension>`: Bundle of ABI and wasm in JSON file. Wasm should probably be included in base64 (nearcore RPC accepts this, so no transformation will be required). The motivation for this is some tooling might want both to avoid having to use two separate files.

What the bundle looks like may be opinionated, maybe it's the same schema as ABI except with an extra key for `code`, or it's a map of `{"abi": ..., "code":}`. The latter might be a bit redundant/confusing because ABI already has a key `abi`.

If it works out cleanly, this can be split into three separate changes:

- [x] Build command that outputs `.wasm`
- [x] Build and include ABI during the command
- [ ] Create bundle output of both

**Comment by austinabell** [comment]
@miraclx, you were looking into this and related tasks, do you want to assign yourself to this?

**Comment by miraclx** [comment]
Sure thing.

**Comment by austinabell** [comment]
re-opening because there are still components relevant in this issue. exalate screwed up the formatting so it's unviewable now. I'll try to fix it later
