### ISSUE TITLE
Docker image missing clang

### ISSUE THREAD

**Issue by MagicGordon** [near/cargo-near#255]
Hi ! Since the project hasn't been open-sourced yet, I've added all the dependencies used in the actual project to the demo's Cargo.toml. Currently, I'm stuck on the missing clang issue, and I'm not sure if other dependencies are also missing. I hope the next version will be able to build this demo：https://github.com/MagicGordon/compile_error

**Comment by dj8yfo** [comment]
@frol @Canvinus looks like the sequence of events to release ammended image would be:
1. merge https://github.com/SourceScan/cargo-near-image/pull/4
2. merge https://github.com/near/cargo-near/pull/254 to have `sourcescan/cargo-near` be rebuilt either automatically within 24 hours or by manual trigger with `0.12.2-rust-1.82.0` tag. Replacing in-place `0.12.1-rust-1.82.0` doesn't sound like a good idea but it can be done as 2b.
2b.   yank  `0.12.1-rust-1.82.0`  image, and have it be rebuilt automatically within 24 hours or by manual trigger

**Comment by dj8yfo** [comment]
fixed in https://hub.docker.com/layers/sourcescan/cargo-near/0.12.2-rust-1.82.0/images/sha256-ed398028ef25d49a7a4b3d96dfe3c358745c8db246d9421b05e8ae937aaaf55a?context=explore
