### ISSUE TITLE
Allow developers to ignore abi generation

### ISSUE THREAD

**Issue by austinabell** [near/cargo-near#34]
The use case would be if someone were using an old version of the SDK or didn't want to enable the feature or build this, but still leverage the convenience of the rust flags set and target configured (and other benefits in the future), they should be able to opt-out of the ABI flow and logic when running the command.

Opinionated how this is done, but my first thought would be something like `--no-abi` for the flag? Share a thought if you think something else is more intuitive

**Comment by austinabell** [comment]
> My intuition, is:
> 
> * When either `--embed-abi` or `--bundle` flag is present, the `abi` feature flag must be activated in the contract. Otherwise, cargo-near reports an error.
> * Without either of those flags, cargo-near should build the contract without ABI. Regardless of which version of sdk the contract uses.

I disagree, the primary use case of ABI is to build the ABI as a file (to be able to generate clients that are checked at compile time). Yes, there will be an interaction with `--embed-abi` and whatever this opt-out functionality would be, but my intuition is that building the wasm, ABI, and bundle would be default. wdyt @itegulov ?

**Comment by itegulov** [comment]
I agree with @austinabell. Given that this is a new flow, I feel like we should encourage people to build ABI and bundle by default. If someone has a strong position on not doing that they will opt-out.

**Comment by miraclx** [comment]
Yeah, experimented a bit more with #31, and I see the need for the `--no-abi` flag, ignore my last comment. So;

 - By default, we export the ABI file, the wasm binary as well as a bundle of the two.
 - When the user specifies `--embed-abi`, we export a binary with ABI embedded, as well the ABI file.
 - When the user specifies `--no-abi`, we only export the wasm binary, without any ABI generation.

**Comment by miraclx** [comment]
Still, though, I don't think everybody wants a bundle. Shouldn't we make that opt-in?

**Comment by itegulov** [comment]
I don't have a strong opinion, but I feel like if you already built WASM and ABI, the overhead for bundle generation is minuscule

**Comment by miraclx** [comment]
That's fair. Since the scope of this issue is small, and intertwined with #31. I've implemented it over there.
