### ISSUE TITLE
Feature request. Record builder image version in contract metadata

### ISSUE THREAD

**Issue by MaksymZavershynskyi** [near/cargo-near#54]
The purpose of the <span class="error">[builder]</span>([https://github.com/near/near-sdk-rs/tree/master/contract-builder](https://github.com/near/near-sdk-rs/tree/master/contract-builder)) is to allow contract developers to prove that certain contract that was deployed to the chain corresponds to the code in github. Therefore if we have multiple versions of the docker image we need to record somehow somewhere (e.g. in Wasm metadata) the version of the image that was used to build it. Consider adding this functionality.

**Comment by dj8yfo** [comment]
Resolved by #134
