### ISSUE TITLE
Duplicate warnings

### ISSUE THREAD

**Issue by miraclx** [near/cargo-near#67]
Using `cargo near` to occasionally build a contract while in active development can be a bit noisy, since both the step that aids ABI extraction and the step that does the actual contract compilation both invoke rustc, which reports the same warnings.

It's different for errors because it fails at the first pass.

Only relevant after #65.

<img width="656" alt="CleanShot 2022-10-15 at 11 57 47@2x" src="https://user-images.githubusercontent.com/16881812/195976122-1141a1a4-5202-46fa-a6c3-f8eda064c3b0.png">

**Comment by itegulov** [comment]
Hmm, I wonder: should we hide warnings while generating ABI?

**Comment by miraclx** [comment]
Yeah, that's reasonable to me.
