### ISSUE TITLE
Unclear error handling when running cargo near build outside of the contract directory 

### ISSUE THREAD

**Issue by AustinBaggio** [near/cargo-near#88]
Versions: 
![image](https://user-images.githubusercontent.com/10964366/199983803-e5cd87c7-dfe7-4937-940e-0d4f6be3696d.png)
Error:
![image](https://user-images.githubusercontent.com/10964366/199983850-a8fd639b-f0f4-46b0-92b2-a0c2a3362f5b.png)

Steps to reproduce: 
1. In the NFT example repo root directory 
2. run `cargo near build --release --embed-abi`
3. EXPECTED: error messaging explaining that you must run the command in the contract source folder 
4. ACTUAL: Hung for 30s+ then returned with the generic error

**Comment by miraclx** [comment]
Hi @AustinBaggio, I can confirm this used to be the behavior of `cargo-near` as at version `0.2`.

We'll be cutting a new release this week that does resolve this, as well as introduce a couple of [QOL improvements](https://github.com/near/cargo-near/blob/a67065839a4821d461ff4d647f5ef6d124a79eca/CHANGELOG.md#Unreleased).

You could install it right away from git, but it also requires the contract uses an up-to-date version of `near-sdk`.

`near-sdk` version `4.1.0` gets [released tomorrow](https://github.com/near/near-sdk-rs/pull/958), and `cargo-near` shortly after that.

**Comment by miraclx** [comment]
@AustinBaggio, both `cargo-near@0.3.0` and `near-sdk@0.4.1` have been released. I believe we can close this now.
