### ISSUE TITLE
`near/*` directories are not crated when building a multi-package project

### ISSUE THREAD

**Issue by itegulov** [near/cargo-near#96]
To reproduce:

1. Go to https://github.com/near/near-sdk-abi/tree/daniyar/near-abi-0.3.0/examples/delegator-generation
2. Ensure that your target directory is clean
3. Run `cargo near build`
4. Receive
```
✗ failed to copy `/path/to/near/near-sdk-abi/target/wasm32-unknown-unknown/debug/delegator_generation.wasm` to `/path/to/near/near-sdk-abi/target/near/delegator_generation/delegator_generation.wasm`
```

The error happens because `target/near/delegator_generation` is not being created

**Comment by dj8yfo** [comment]
fixed by #134
